sudo: required

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc

# Build steps
script:
  - g++ -c src/*.cpp

before_deploy:
  - g++ src/Main.cpp src/parselib.cpp src/tokenlib.cpp -o C-code-beautifier

deploy:
  provider: releases
  api_key:
    secure: "0NkLHWTOVWayx/uScp5qiAa2xqeDf4wikmvgjVsG9JEV6zFxHBjM0tmOwXn7FpLpsfP1mJjCfoZX1L+ZyUuigv39KYbqddcYjGZ2hefLL65FL2lRNUSu/lFxBvs24W+TCGpR6ypQ1uDk+2gyVmup0wtfEIF1A7SePECsYyOS4iC7gVPf9bCnyHdoRPcQxvF4NTVlMnX1ND7NrYk0T5PYip87VoNAs9OR9VVFw5nufKll31DCz1UntXHPdCB7wkDiGEJwNE9fQV4dqdpqbYmvWfk8Au0Aa6oSDrtYwAhYdbfXDVa1aRwIXPPBktbHq9DIVq5xPyVuqeGi1GcHbu9TUhvSmpLM4nUm9QBPzRE+8b6QtgXwdPveiT/TKCCKIXBI88WRWfNp0pZcUyQfR71BZUdYistSzv4DPYxVUJY2cxVlYck9o2Axxd4vb9pDMmg2MsnH82l6arSXyYTunL45T6CgJCEO0NuP+k9TECduEnD3awcAT7Uj7iH9ZfHXxHeYwmDZ1z11dPyzFGe5PQNc6seuECogtF5hBwffXfwomHuVry8UmBj2/IWO2MuxA/NhingHY0HE2AbunVX5siXElC8h7uoNsyGJRLBGBP3Sio4nKknwBNAlDKfRtxFSjKXG5bKyTrnCEp+s1pdN9Rak+U+zCcWp8qBxH4cu87u1Fbc="
  file: $TRAVIS_BUILD_DIR/C-Code-Beautifier
  skip_cleanup: true
  on:
    repo: ayonious/C-Code-Beautifier
    tags: true
